### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ReeZer2** [jusdepatate/4lbion#1]
![image](https://user-images.githubusercontent.com/63300653/86268926-a6d8b380-bbd1-11ea-90d0-37e0e49f95a3.png)
My pc is 64bit

**Comment by bc1bb** [comment]
Hi, sorry I just saw your issue.
I just noticed that the way I check if the user has a 32 or 64 bits processor doesn't work on Windows, but it does on Linux IIRC.
Thanks for your issue i'll remove the check and re make it whenever i'm not lazy anymore :)
